### ISSUE TITLE
Throws OSError

### ISSUE THREAD

**Issue by hcaga** [sarperavci/MXS#2]
Sometimes it throws 
OSError: [Errno 24] Too many open files: 'vulnerable_urls.txt'

**Comment by sarperavci** [comment]
In which configuration are you generally getting this error?

**Comment by hcaga** [comment]
I tested this on my url list.:


─$ python3 ./MXS.py -i ../../../HNCFuzzing/output/REDACTED.com/fuzzing/ALL_STATUS_URLS.TXT -c 600
 [i] Starting scan with 600 concurrency
 [i] Output file: vulnerable_urls.txt
 [i] Timeout: 15 seconds
Traceback (most recent call last):ectable URLs
  File "/home/kali/tools/HNCTools/HNCBugBounty/tools/MXS/./MXS.py", line 21, in <module>
    scanner.run()
  File "/home/kali/tools/HNCTools/HNCBugBounty/tools/MXS/func.py", line 124, in run
    asyncio.run(self.scan())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kali/tools/HNCTools/HNCBugBounty/tools/MXS/func.py", line 114, in scan
    self.saveInjectablesToFile()
  File "/home/kali/tools/HNCTools/HNCBugBounty/tools/MXS/func.py", line 57, in saveInjectablesToFile
    with open(self.output, "a") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: 'vulnerable_urls.txt'

**Comment by sarperavci** [comment]
The opened output file may not close due to an unknown issue. We will work on resolving this bug. As a workaround, you can specify another output file with the `-o <output>` parameter, which will likely fix your issue temporarily. You can also try running it with another version of Python, especially Python 3.7, where we observe the best concurrency performance.

**Comment by hcaga** [comment]
I think I might try running this on Python 3.7. The ```-o <output>``` parameter still throws an OSError.

Thanks a lot! Great work, by the way!

**Comment by M-Enes** [comment]
I think it might be caused by your system's open file limit. Could you try restarting your system if you are using it for a long time?

**Comment by sarperavci** [comment]
Could you inspect the output of the `lsof` command, which will show the open files on your OS and determine whether this error is related to `MXS` or not?

**Comment by M-Enes** [comment]
File save mechanism changed with this pull request. It also fixed this issue. Thanks for this issue.
