### ISSUE TITLE
Wordlist?

### ISSUE THREAD

**Issue by krivadna** [sarperavci/MXS#5]
Can we not scan single url? Also why did u use wordlists.txt when all we hv to scan us a url..

**Comment by sarperavci** [comment]
You can scan a single URL or millions of URLs. There's no minimum limit. Save your URLs to a file and specify it using the `-i` parameter. What's the issue exactly?

**Comment by krivadna** [comment]
And can we directly use urls file from sub finder paramfinder etc

**Comment by M-Enes** [comment]
Yeah ,your url list should be formed like any of these:
https://target.com/somepage?someparam&anotherparam
https://target.com/somepage?someparam=&anotherparam=
https://target.com/somepage?someparam=somevalue&anotherparam=anothervalue

**Comment by krivadna** [comment]
Jazak Allah brother..

**Comment by krivadna** [comment]
Also wanted to ask u, which tool u use to find parameters to scan with this tool

**Comment by M-Enes** [comment]
We don't use any specific tool for it now. But, you can use tool which creates output in a convenient form.
